
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfgpjwjpshnanjrxhmnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mZ3Bqd2pwc2huYW5qcnhobW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNzAwNDgsImV4cCI6MjA1Nzc0NjA0OH0.eClbpmE2hNvSr7R3heIb_atkmFneCas2Y61g3nUZAHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true
    },
    db: {
      schema: 'public' // Using 'public' schema to match type definitions
    }
  }
);

// Alias for api schema tables
export const apiSchema = {
  profiles: () => supabase.from('profiles').schema('api'),
  game_sessions: () => supabase.from('game_sessions').schema('api'),
  game_players: () => supabase.from('game_players').schema('api'),
  game_invites: () => supabase.from('game_invites').schema('api'),
  notifications: () => supabase.from('notifications').schema('api'),
};

// Helper function to check if a Supabase error is a 'not found' error
export const isNotFoundError = (error: any): boolean => {
  return error?.code === 'PGRST116' || // PostgreSQL not found
         error?.message?.includes('No rows found') ||
         error?.details?.includes('Results contain 0 rows');
};

// Helper function for safe type casting of Supabase query results
export function safeDataCast<T>(data: any): T[] {
  if (!data) return [] as T[];
  return data as T[];
}

// Helper function for safely handling single record results
export function safeSingleDataCast<T>(data: any): T | null {
  if (!data) return null;
  return data as T;
}
